[package]
name = "assets"
version = "0.1.0"
edition = "2024"

[dependencies]
protocol = { path = "../protocol" }
bevy.workspace = true
lightyear.workspace = true
avian3d.workspace = true

[lints]
workspace = true
